### ISSUE TITLE
Should be invalid if the input is empty string in RequiredValidator

### ISSUE THREAD

**Issue by keito-jp** [go-jstmpl/ts-jsvalidator#12]
Should be invalid if the input is empty string in RequiredValidator.
Now, it is valid when the input is `""`.

**Comment by minodisk** [comment]
When check a string is empty or not, `minLength` validator should be used.

Reason: The spec of `required` is `An object instance is valid against this keyword if its property set contains all elements in this keyword's array value`. So the existence of the value of property should be checked, but which the value is empty or not shouldn't be checked.

See also [JSON Schema: interactive and non interactive validation](http://json-schema.org/latest/json-schema-validation.html#anchor61)
