### ISSUE TITLE
Check the value of the required fields isn't null

### ISSUE THREAD

**Issue by minodisk** [go-jstmpl/ts-jsvalidator#14]
## Definition in RFC

> ### 5.15. required
> 
> The value of this keyword MUST be an array. This array MUST have at least one element. Elements of this array MUST be strings, and MUST be unique.
> 
> An object instance is valid against this keyword if its property set contains all elements in this keyword's array value.

via: http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.15

Sounds we should check the existence of the properties listed in `required`, nor the value. But this is useless for validation...
We want to check the existence of the **value** for the properties listed in `required`.

## Improvement to

If the value of `required` property is `null`, the required validator should return error.

**Comment by keito-jp** [comment]
The required validator already return an error if  the value of `required` property is `null`. But it's not tested, so add test case when the value of `required` property is `null`.
